-- DO NOT EDIT THIS FILE DIRECTLY
-- CREATE A COPY TO EDIT, OTHERWISE YOUR CHANGES MAY BE LOST ON UPDATES

-- SORT: ShipSort default sorter v3 for ShipSort v5

-- List of items to never sort (by internal name)
BLACKLIST = {}

-- List of scrap items to interpret as tools (by internal name)
TOOLS = { "KnifeItem", "ShotgunItem" }

-- Fancy mode - Sorts the scrap on the wall in a layout similar to ScrapMagic
fancy_mode = true

-- Disable cruiser:
--unlockables[UNLOCKABLE_CRUISER] = false

-- Disable cupboard:
--unlockables[UNLOCKABLE_CUPBOARD] = false

-- Disable fridge:
--unlockables[UNLOCKABLE_FRIDGE] = false

-- On which moons should the tools be put on top of the cruiser (instead of inside)
cruiser_top_moons = {
    3,  -- company
    8,  -- offense
    10, -- artifice
    12, -- embrion
}



print(script, "v3", "on", about)
expect_version(5)

function contains(table, i)
    for k, v in ipairs(table) do
        if v == i then
            return true, k
        end
    end
    return false
end

cruiser_top = false
for _, v in ipairs(cruiser_top_moons) do
    if type(v) == "string" then
        if moon.name == v then
            cruiser_top = true
            break
        end
    else
        if moon.id == v then
            cruiser_top = true
            break
        end
    end
end

function randomize(position)
    return randomize_scaled(position, 0.05)
end

function randomize_scaled(position, scale)
    return Vector3(position.x + (math.random() - 0.5) * scale, position.y, position.z + (math.random() - 0.5) * scale)
end

function randomize_xy_scaled(position, scale)
    return Vector3(position.x + (math.random() - 0.5) * scale, position.y + (math.random() - 0.5) * scale, position.z)
end

raycast_cache = {}
function below(position, name)
    if name == nil then
        return randomize(raycast(position))
    elseif raycast_cache[name] ~= nil then
        return randomize(raycast_cache[name])
    else
        raycast_cache[name] = raycast(position)
        return randomize(raycast_cache[name])
    end
end

function cupboard_or(cupboard_pos, fallback_pos)
    if unlockables[UNLOCKABLE_CUPBOARD] then
        return ItemPos(randomize_xy_scaled(cupboard_pos, 0.02)):with_parent(PARENT_CUPBOARD)
    elseif fallback_pos == nil then
        return nil
    else
        return ItemPos(randomize_scaled(raycast(fallback_pos), 0.02))
    end
end

function cupboard_or_rot(cupboard_pos, fallback_pos, fallback_rot)
    if unlockables[UNLOCKABLE_CUPBOARD] then
        return ItemPos(randomize_xy_scaled(cupboard_pos, 0.02)):with_parent(PARENT_CUPBOARD)
    else
        return ItemPos(randomize_scaled(raycast(fallback_pos), 0.02)):with_rotation(fallback_rot)
    end
end

function cupboard_rot_or_rot(cupboard_pos, cupboard_rot, fallback_pos, fallback_rot)
    if unlockables[UNLOCKABLE_CUPBOARD] then
        return ItemPos(randomize_xy_scaled(cupboard_pos, 0.02)):with_parent(PARENT_CUPBOARD):with_rotation(cupboard_rot)
    else
        return ItemPos(randomize_scaled(raycast(fallback_pos), 0.02)):with_rotation(fallback_rot)
    end
end

function first_x_on_cruiser(item, x, cruiser_pos, cruiser_top_pos, cruiser_rot, fallback_pos)
    if unlockables[UNLOCKABLE_CRUISER] and item.index - 1 < x then
        return ItemPos((function()
            if cruiser_top then
                return cruiser_top_pos
            else
                return cruiser_pos
            end
        end)()):with_parent(PARENT_CRUISER):with_rotation(cruiser_rot)
    else
        return fallback_pos
    end
end

item_on_cruiser = {}
function first_x_on_cruiser_where(item, x, predicate, cruiser_pos, cruiser_top_pos, cruiser_rot, fallback_pos)
    if item_on_cruiser[item.name] == nil then
        item_on_cruiser[item.name] = 0
    end
    if unlockables[UNLOCKABLE_CRUISER] and predicate(item) and item_on_cruiser[item.name] < x then
        item_on_cruiser[item.name] = item_on_cruiser[item.name] + 1
        return ItemPos((function()
            if cruiser_top then
                return cruiser_top_pos
            else
                return cruiser_pos
            end
        end)()):with_parent(PARENT_CRUISER):with_rotation(cruiser_rot)
    else
        return fallback_pos
    end
end

fallback_tool_items = {}
last_fallback_tool_items = {}
fallback_tool_items_c = 0
function fallback_tool_item(i, v)
    if fallback_tool_items[v.name] == nil then
        if fallback_tool_items_c % 2 == 0 then
            fallback_tool_items[v.name] = raycast(Vector3(0 + fallback_tool_items_c / 2, RAYCAST_SHIP_FLOOR, -6.4))
        else
            fallback_tool_items[v.name] = raycast(Vector3(0 + (fallback_tool_items_c - 1) / 2, RAYCAST_SHIP_FLOOR, -7.4))
        end
        fallback_tool_items_c = fallback_tool_items_c + 1
        last_fallback_tool_items = { v.name }
    end
    if last_fallback_tool_items[1] == v.name then
        table.insert(last_fallback_tool_items, i)
    end
    retval[i] = fallback_tool_items[v.name]
end

retval = {}

-- Y
RAYCAST_SHIP_TOP = 4.4
RAYCAST_SHIP_FLOOR = 0.2
SHIP_TOP = 4.15
SHIP_LEVER_LEFT = 1.2
SHIP_LEVER_RIGHT = 1.35
SHIP_FLOOR = 0
CUPBOARD_ABOVE = 2.88
CUPBOARD_TOP = 2.2
CUPBOARD_MIDDLE_1 = 1.5
CUPBOARD_MIDDLE_2 = 1.025
CUPBOARD_BOTTOM = 0.24
CRUISER_ABOVE = 2.4
CRUISER_TOP = 1.17
CRUISER_MIDDLE = 0.4
CRUISER_BOTTOM = -0.12
CRUISER_FLOOR = -0.5
FRIDGE_FREEZER_TOP = 1.7
FRIDGE_FREEZER_BOTTOM = 1.3
FRIDGE_TOP = 0.75
FRIDGE_MIDDLE = 0.35
FRIDGE_BOTTOM = -0.21
FRIDGE_CONTAINERS = -0.5

-- X
SHIP_DOOR = -6.8
CRUISER_LEFT = -1.14
CRUISER_RIGHT = 1.14

-- Z
CRUISER_FRONT = 0.35

tools_only = false
scrap_only = false
cruiser_only = false
argc = #args
if argc > 1 then
    error("Invalid arguments")
elseif argc <= 0 then
elseif args[1] == "tools" then
    tools_only = true
elseif args[1] == "scrap" then
    scrap_only = true
elseif args[1] == "cruiser" then
    cruiser_only = true
else
    error("Invalid argument: " .. args[1])
end

layout_twohand = {}
layout_twohand_c = 0
layout_onehand = {}
layout_onehand_c = 0
dawg_position = 0
for i, v in pairs(items) do
    if v.name == "ClipboardManual" or v.name == "StickyNoteItem" or v.name == "CompanyCruiserManual" or contains(BLACKLIST, v.name) then
        -- skip these items

    elseif v.name == "ZeddogPlushie" then

        :: dawg_retry ::
        dawg_position = dawg_position + 1

        if dawg_position == 1 then
            -- terminal dawg
            retval[i] = ItemPos(Vector3(-0.9, -0.75, 0.35)):with_relative(RELATIVE_TERMINAL)
        elseif dawg_position == 2 then
            -- dawg swim
            if unlockables[UNLOCKABLE_GOLDFISH] then
                retval[i] = ItemPos(Vector3(0, 0, 0)):with_relative(RELATIVE_GOLDFISH)
            else
                goto dawg_retry
            end
        elseif dawg_position == 3 then
            -- dawg clean
            if unlockables[UNLOCKABLE_SHOWER] then
                retval[i] = ItemPos(Vector3(0, -0.1, -1.05)):with_relative(RELATIVE_SHOWER):with_rotation(90)
            else
                goto dawg_retry
            end
        elseif dawg_position == 4 then
            -- dawg date
            if unlockables[UNLOCKABLE_ROMANTIC_TABLE] and v.index < v.count then
                retval[i] = ItemPos(Vector3(0, 0.55, 0.6)):with_relative(RELATIVE_ROMANTIC_TABLE):with_rotation(-90)
            else
                dawg_position = dawg_position + 1 -- skip next one as well
                goto dawg_retry
            end
        elseif dawg_position == 5 then
            -- dawg date pt 2
            if unlockables[UNLOCKABLE_ROMANTIC_TABLE] then
                retval[i] = ItemPos(Vector3(0, 0.55, -0.6)):with_relative(RELATIVE_ROMANTIC_TABLE):with_rotation(90)
            else
                goto dawg_retry
            end
        elseif dawg_position == 6 then
            -- hot dawg
            if unlockables[UNLOCKABLE_MICROWAVE] then
                retval[i] = ItemPos(Vector3(0, -0.2, 0)):with_parent(PARENT_MICROWAVE):with_rotation_mode(ROTATE_NONE)
            else
                goto dawg_retry
            end
        elseif dawg_position == 7 then
            -- 1% chance to summon gawd
            if math.random() < 0.01 then
                retval[i] = ItemPos(Vector3(-10.2, 1.4, -6.6)):with_rotation(180)
                print("gawd has appeared")
            else
                goto dawg_retry
            end
        elseif unlockables[UNLOCKABLE_DOG_HOUSE] then
            -- dawg house
            retval[i] = ItemPos(Vector3(math.random() * 1.6 - 0.8, 0.05, math.random() * 0.8)):with_relative(RELATIVE_DOG_HOUSE):with_rotation(math.random(360))
        else
            -- dawg sad :(
            retval[i] = Vector3(9.2, 1.4, -7.075)
        end
    elseif v.name == "KnifeItem" then
        retval[i] = first_x_on_cruiser(v, 1, Vector3(CRUISER_RIGHT, CRUISER_TOP, -2.4), Vector3(-0.5, CRUISER_ABOVE, -3.7), -90, cupboard_or_rot(Vector3(-1.9, 0.6, CUPBOARD_MIDDLE_2), Vector3(-2.5, 3, -6.65), -90))
    elseif v.name == "ShotgunItem" and v.type == "ShotgunItem" then
        retval[i] = first_x_on_cruiser_where(v, 2, (function(item)
            return item.arg >= 2
        end), Vector3(CRUISER_RIGHT + 0.04, CRUISER_TOP, -1.2), Vector3(1.3, CRUISER_ABOVE, -3.7), 0, Vector3(8.9 - (0.15 * v.arg), SHIP_LEVER_LEFT, -5.5))

    elseif v.name == "LungApparatus" or v.name == "LungApparatusTurnedOff" then
        if fancy_mode then
            retval[i] = ItemPos(Vector3(1.475, 3.45, -8.6)):with_rotation(90)
        else
            retval[i] = ItemPos(Vector3(SHIP_DOOR, SHIP_TOP, -6.65)):with_rotation(-90)
        end
    elseif v.name == "KiwiBabyItem" then
        retval[i] = below(Vector3(4.85, RAYCAST_SHIP_TOP, -4), v.name)
    elseif v.name == "RedLocustHive" then
        retval[i] = Vector3(SHIP_DOOR, SHIP_TOP, -5.65)
    elseif v.name == "SoccerBall" then
        retval[i] = Vector3(9, SHIP_LEVER_RIGHT, -8.25)
    elseif v.name == "WhoopieCushion" then
        retval[i] = Vector3(SHIP_DOOR, SHIP_TOP, -7.75)
    elseif unlockables[UNLOCKABLE_FRIDGE] and v.name == "SeveredFootLOD0" then
        retval[i] = ItemPos(randomize(Vector3(0.25, FRIDGE_MIDDLE, 0.2))):with_parent(PARENT_FRIDGE)
    elseif unlockables[UNLOCKABLE_FRIDGE] and v.name == "SeveredHandLOD0" then
        retval[i] = ItemPos(randomize(Vector3(-0.25, FRIDGE_MIDDLE, 0.2))):with_parent(PARENT_FRIDGE)
    elseif unlockables[UNLOCKABLE_FRIDGE] and v.name == "Bone" then
        retval[i] = ItemPos(randomize(Vector3(0, FRIDGE_BOTTOM, 0.2))):with_parent(PARENT_FRIDGE)
    elseif unlockables[UNLOCKABLE_FRIDGE] and v.name == "SeveredThighLOD0" then
        retval[i] = ItemPos(randomize(Vector3(0, FRIDGE_TOP, 0.05))):with_parent(PARENT_FRIDGE)
    elseif unlockables[UNLOCKABLE_FRIDGE] and v.name == "Tongue" then
        retval[i] = ItemPos(randomize_scaled(Vector3(0.5, FRIDGE_CONTAINERS, 0.05 + (math.random() - 0.5) * 0.8), 0.02)):with_parent(PARENT_FRIDGE)
    elseif unlockables[UNLOCKABLE_FRIDGE] and v.name == "Ear" then
        retval[i] = ItemPos(randomize_scaled(Vector3(-0.3, FRIDGE_CONTAINERS - 0.005, 0.05 + (math.random() - 0.5) * 0.8), 0.02)):with_parent(PARENT_FRIDGE)
    elseif unlockables[UNLOCKABLE_FRIDGE] and v.name == "HeartContainer" then
        retval[i] = ItemPos(randomize(Vector3(0, FRIDGE_FREEZER_BOTTOM, 0.4))):with_parent(PARENT_FRIDGE):with_rotation(-90)
    elseif unlockables[UNLOCKABLE_FRIDGE] and v.name == "RibcageBone" then
        retval[i] = ItemPos(randomize(Vector3(0, FRIDGE_FREEZER_TOP, -0.2))):with_parent(PARENT_FRIDGE):with_rotation(90)

    elseif v.name == "WalkieTalkie" then
        retval[i] = cupboard_or(Vector3(-0.45, 0.5, CUPBOARD_MIDDLE_1), Vector3(-3.7, RAYCAST_SHIP_FLOOR, -6.6))
    elseif v.name == "BBFlashlight" then
        retval[i] = cupboard_or(Vector3(-1.1, 0.55, CUPBOARD_MIDDLE_1), Vector3(-4.1, RAYCAST_SHIP_FLOOR, -6.6))
    elseif v.name == "ShovelItem" then
        retval[i] = first_x_on_cruiser(v, 4, Vector3(CRUISER_RIGHT, CRUISER_MIDDLE, -2), Vector3(-1.3, CRUISER_ABOVE, -3.7), -90, cupboard_or_rot(Vector3(-1.5, 0.3, CUPBOARD_MIDDLE_2), Vector3(-4.5, SHIP_FLOOR, -6.8), -90))
    elseif v.name == "LockPickerItem" then
        retval[i] = cupboard_or(Vector3(-2, 0.5, CUPBOARD_TOP), Vector3(-1.8, RAYCAST_SHIP_FLOOR, -6.8)):with_rotation(90)
    elseif v.name == "FlashlightItem" then
        retval[i] = cupboard_or(Vector3(-1.4, 0.45, CUPBOARD_MIDDLE_1), Vector3(-4.1, RAYCAST_SHIP_FLOOR, -7.2))
    elseif v.name == "StunGrenade" then
        retval[i] = cupboard_or(Vector3(-0.8, 0.59, CUPBOARD_MIDDLE_1), Vector3(-3.7, RAYCAST_SHIP_FLOOR, -7.35)):with_rotation(-90)
    elseif v.name == "Boombox" then
        retval[i] = cupboard_or(Vector3(-0.3, 0.5, CUPBOARD_ABOVE), Vector3(-1.1, RAYCAST_SHIP_FLOOR, -6.8))
    elseif v.name == "TZPChemical" then
        retval[i] = cupboard_or(Vector3(-1.54, 0.4, CUPBOARD_TOP), Vector3(-3.3, RAYCAST_SHIP_FLOOR, -6.525)):with_rotation(-90)
    elseif v.name == "PatcherGunItem" then
        retval[i] = cupboard_or_rot(Vector3(-1.2, 0.6, CUPBOARD_TOP), Vector3(-4.9, RAYCAST_SHIP_FLOOR, -6.5), -90)
    elseif v.name == "JetpackItem" then
        retval[i] = cupboard_or(Vector3(-0.3, 0.2, CUPBOARD_BOTTOM), Vector3(-5.8, RAYCAST_SHIP_FLOOR, -6.8))
    elseif v.name == "SprayPaintItem" then
        retval[i] = cupboard_or(Vector3(-1.7, 0.55, CUPBOARD_MIDDLE_1), Vector3(-3.3, RAYCAST_SHIP_FLOOR, -7.3)):with_rotation(-90)
    elseif v.name == "WeedKillerItem" then
        retval[i] = first_x_on_cruiser(v, math.huge, Vector3(CRUISER_RIGHT, CRUISER_MIDDLE, -0.77), Vector3(-0.9, CRUISER_ABOVE, -3.7), -90, cupboard_or(Vector3(-2, 0.55, CUPBOARD_MIDDLE_1), Vector3(-2.5, SHIP_FLOOR, -7.3)):with_rotation(-90))
    elseif v.name == "BeltBagItem" then
        if v.type == "BeltBagItem" and v.arg > 0 then
            if unlockables[UNLOCKABLE_CRUISER] then
                if item_on_cruiser[v.name] == nil then
                    item_on_cruiser[v.name] = 0
                end
                if cruiser_top then
                    retval[i] = ItemPos(Vector3(1.1, CRUISER_ABOVE + item_on_cruiser[v.name] * 0.3, -2.5)):with_parent(PARENT_CRUISER):with_rotation(-90)
                else
                    retval[i] = ItemPos(Vector3(-0.8, CRUISER_BOTTOM + item_on_cruiser[v.name] * 0.3, CRUISER_FRONT)):with_parent(PARENT_CRUISER):with_rotation(90)
                end
                item_on_cruiser[v.name] = item_on_cruiser[v.name] + 1
            else
                retval[i] = cupboard_rot_or_rot(Vector3(-0.7, 0.5, CUPBOARD_TOP + 0.35), 180, Vector3(-5, RAYCAST_SHIP_FLOOR, -7.85), 0)
            end
        else
            retval[i] = cupboard_or(Vector3(-0.35, 0.5, CUPBOARD_TOP), Vector3(-5, RAYCAST_SHIP_FLOOR, -7.1))
        end
    elseif v.name == "Key" then
        retval[i] = first_x_on_cruiser(v, 4, Vector3(CRUISER_LEFT, CRUISER_MIDDLE, -0.7), Vector3(-0.1, CRUISER_ABOVE, -3.7), -90, cupboard_or(Vector3(-0.3, 0.6, CUPBOARD_MIDDLE_2), Vector3(8.6, 2, -6.6)))
    elseif v.name == "ShotgunShell" then
        retval[i] = first_x_on_cruiser(v, 2, Vector3(CRUISER_LEFT, CRUISER_TOP, -0.7), Vector3(0.9, CRUISER_ABOVE, -3.7), -90, Vector3(8.75, SHIP_LEVER_LEFT, -6.05))

    elseif v.name == "RadarBoosterDevice" then
        retval[i] = first_x_on_cruiser_where(v, 1, (function(item)
            return item.arg
        end), Vector3(0, CRUISER_BOTTOM, CRUISER_FRONT), Vector3(1.1, CRUISER_ABOVE, -1.7), 0, nil)
        if retval[i] == nil then
            if v.index == v.count and unlockables[UNLOCKABLE_CRUISER] and item_on_cruiser[v.name] ~= 1 then
                if cruiser_top then
                    retval[i] = ItemPos(Vector3(1.1, CRUISER_ABOVE, -1.7)):with_parent(PARENT_CRUISER)
                else
                    retval[i] = ItemPos(Vector3(0, CRUISER_BOTTOM, CRUISER_FRONT)):with_parent(PARENT_CRUISER)
                end
            else
                fallback_tool_item(i, v)
            end
        end
    elseif v.name == "MappingDevice" then
        if unlockables[UNLOCKABLE_PLUSHIE_PAJAMA_MAN] then
            -- ipad kid
            retval[i] = ItemPos(Vector3(-0.25, -0.1, -0.4)):with_relative(RELATIVE_PLUSHIE_PAJAMA_MAN):with_rotation(-90)
        else
            fallback_tool_item(i, v)
        end

    elseif not v.scrap or contains(TOOLS, v.name) then
        -- Tool item
        fallback_tool_item(i, v)
    elseif tools_only or cruiser_only then
        -- Minor optimization, we can avoid the following code if the results are going to be ignored
    elseif v.large then
        -- Two hand item
        if fancy_mode then
            if layout_twohand[v.name] == nil then
                layout_twohand[v.name] = Vector3(-5.8 + layout_twohand_c * 0.7, 3.5, -5)
                layout_twohand_c = layout_twohand_c + 1
            end
            retval[i] = ItemPos(layout_twohand[v.name] + Vector3(0, math.floor((v.index - 1) / 5) * 0.05, (v.index - 1) % 5 * 0.05)):with_rotation(-90)
        else
            retval[i] = below(Vector3(-4.5, RAYCAST_SHIP_TOP, -5.25), 2)
        end
    else
        -- One hand item
        if fancy_mode then
            if layout_onehand[v.name] == nil then
                x = math.floor(layout_onehand_c / 4)
                layout_onehand[v.name] = Vector3(-5.8 + x * 0.6, 0.25 + ((layout_onehand_c % 4) + (x % 2 ~= 0 and 0.5 or 0)) * 0.7, -5)
                layout_onehand_c = layout_onehand_c + 1
            end
            retval[i] = ItemPos(layout_onehand[v.name] + Vector3(0, math.floor((v.index - 1) / 5) * 0.05, (v.index - 1) % 5 * 0.05)):with_rotation(-90)
        else
            retval[i] = below(Vector3(-2.25, RAYCAST_SHIP_TOP, -5.25), 1)
        end
    end
end

if fallback_tool_items_c % 2 ~= 0 then
    pos = raycast(Vector3(0 + (fallback_tool_items_c - 1) / 2, RAYCAST_SHIP_FLOOR, -6.9))
    for _, i in ipairs(last_fallback_tool_items) do
        if _ > 1 then
            retval[i] = randomize_scaled(pos, 0.02)
        end
    end
end

if tools_only or scrap_only or cruiser_only then
    for i, v in pairs(retval) do
        if tools_only then
            if items[i].scrap and not contains(TOOLS, items[i].name) then
                retval[i] = nil
            end
        elseif scrap_only then
            if not items[i].scrap or contains(TOOLS, items[i].name) then
                retval[i] = nil
            end
        elseif cruiser_only then
            if v.parent ~= PARENT_CRUISER then
                retval[i] = nil
            end
        end
    end
end

return retval
