-- DO NOT EDIT THIS FILE DIRECTLY
-- CREATE A COPY TO EDIT, OTHERWISE YOUR CHANGES MAY BE LOST ON UPDATES

SKIPPED_ITEMS = { "ClipboardManual", "StickyNoteItem", "CompanyCruiserManual", "Boombox" }
DOORFRAME_ITEMS = { "LungApparatus", "LungApparatusTurnedOff", "SoccerBall", "WhoopieCushion" }
SUMMON_CIRCLE_ITEMS = {  }
SUMMON_CIRCLE_STACK = false -- creates one circle per item type and stacks them on top of each other
CUPBOARD_TOP_ITEMS = { "ExtensionLadderItem", "RadarBoosterDevice", "JetpackItem" }
CUPBOARD_SHELF_A_ITEMS = { "KnifeItem", "ShotgunItem", "ShovelItem" }
CUPBOARD_SHELF_B_ITEMS = { "Key", "ShotgunShell", "BBFlashlight", "FlashlightItem" }
CUPBOARD_SHELF_C_ITEMS = { "BeltBagItem", "StunGrenade", "WalkieTalkie", "SprayPaintItem" }
CUPBOARD_SHELF_D_ITEMS = { "LockPickerItem", "TZPChemical", "WeedKillerItem", "PatcherGunItem" }
EXCLUDE_TOOLS_FROM_SCRAP_LAYOUT = true -- leaves remaining tools unsorted (if false, any undefined tools will be sorted with the remaining scrap on the wall)



print(script, "on", about)
expect_version(4)

function contains(table, i)
    for _, v in ipairs(table) do
        if v == i then
            return true
        end
    end
    return false
end

CIRCLE_CENTER = Vector3(7, 0, -6.75)
CIRCLE_RADIUS = 1

circle = {}
circle_c = 0

CUPBOARD_MIN = Vector3(-1.6, 0.5, 0)
CUPBOARD_MAX = Vector3(-0.6, 0.5, 0)

CUPBOARD_TOP = 2.88;
CUPBOARD_SHELF_A = 2.2;
CUPBOARD_SHELF_B = 1.5;
CUPBOARD_SHELF_C = 1.025;
CUPBOARD_SHELF_D = 0.24;

cupboard_top = {}
cupboard_top_c = 0
cupboard_shelf_a = {}
cupboard_shelf_a_c = 0
cupboard_shelf_b = {}
cupboard_shelf_b_c = 0
cupboard_shelf_c = {}
cupboard_shelf_c_c = 0
cupboard_shelf_d = {}
cupboard_shelf_d_c = 0

function cupboard_sort(retval, cupboard_l, cupboard_c, cupboard_y)
    if not unlockables[UNLOCKABLE_CUPBOARD] then
        return
    end

    margin = (CUPBOARD_MAX - CUPBOARD_MIN) / (cupboard_c + 1)

    x = 0
    for _, v in pairs(cupboard_l) do
        x = x + 1
        for _, i in ipairs(v) do
            retval[i] = ItemPos(CUPBOARD_MIN + margin * x + Vector3(0, math.floor((items[i].index - 1) / 5) * 0.05, (items[i].index - 1) % 5 * 0.05 + cupboard_y)):with_parent(PARENT_CUPBOARD):with_rotation(-90)
        end
    end
end

layout_twohand = {}
layout_twohand_c = 0
layout_onehand = {}
layout_onehand_c = 0

retval = {}

for i, v in pairs(items) do
    if contains(SKIPPED_ITEMS, v.name) then
    elseif contains(DOORFRAME_ITEMS, v.name) then
        if v.count <= 1 then
            x = 0.5
        else
            x = (v.index - 1) / (v.count - 1)
        end
        retval[i] = ItemPos(Vector3(-6.8, 4.175, -5 + (-3.5 * x))):with_rotation(-90)
    elseif contains(SUMMON_CIRCLE_ITEMS, v.name) then
        if circle[v.name] == nil then
            circle[v.name] = {}
        end
        table.insert(circle[v.name], i)
        circle_c = circle_c + 1
    elseif contains(CUPBOARD_TOP_ITEMS, v.name) then
        if cupboard_top[v.name] == nil then
            cupboard_top[v.name] = {}
            cupboard_top_c = cupboard_top_c + 1
        end
        table.insert(cupboard_top[v.name], i)
    elseif contains(CUPBOARD_SHELF_A_ITEMS, v.name) then
        if cupboard_shelf_a[v.name] == nil then
            cupboard_shelf_a[v.name] = {}
            cupboard_shelf_a_c = cupboard_shelf_a_c + 1
        end
        table.insert(cupboard_shelf_a[v.name], i)
    elseif contains(CUPBOARD_SHELF_B_ITEMS, v.name) then
        if cupboard_shelf_b[v.name] == nil then
            cupboard_shelf_b[v.name] = {}
            cupboard_shelf_b_c = cupboard_shelf_b_c + 1
        end
        table.insert(cupboard_shelf_b[v.name], i)
    elseif contains(CUPBOARD_SHELF_C_ITEMS, v.name) then
        if cupboard_shelf_c[v.name] == nil then
            cupboard_shelf_c[v.name] = {}
            cupboard_shelf_c_c = cupboard_shelf_c_c + 1
        end
        table.insert(cupboard_shelf_c[v.name], i)
    elseif contains(CUPBOARD_SHELF_D_ITEMS, v.name) then
        if cupboard_shelf_d[v.name] == nil then
            cupboard_shelf_d[v.name] = {}
            cupboard_shelf_d_c = cupboard_shelf_d_c + 1
        end
        table.insert(cupboard_shelf_d[v.name], i)
    elseif not v.scrap and EXCLUDE_TOOLS_FROM_SCRAP_LAYOUT then
    elseif v.large then
        if layout_twohand[v.name] == nil then
            layout_twohand[v.name] = Vector3(-5.8 + layout_twohand_c * 0.7, 3.5, -5)
            layout_twohand_c = layout_twohand_c + 1
        end
        retval[i] = ItemPos(layout_twohand[v.name] + Vector3(0, math.floor((v.index - 1) / 5) * 0.05, (v.index - 1) % 5 * 0.05)):with_rotation(-90)
    else
        if layout_onehand[v.name] == nil then
            x = math.floor(layout_onehand_c / 4)
            layout_onehand[v.name] = Vector3(-5.8 + x * 0.6, 0.25 + ((layout_onehand_c % 4) + (x % 2 ~= 0 and 0.5 or 0)) * 0.7, -5)
            layout_onehand_c = layout_onehand_c + 1
        end
        retval[i] = ItemPos(layout_onehand[v.name] + Vector3(0, math.floor((v.index - 1) / 5) * 0.05, (v.index - 1) % 5 * 0.05)):with_rotation(-90)
    end
end

if circle_c <= 1 then
    for _, v in pairs(circle) do
        for _, i in ipairs(v) do
            retval[i] = ItemPos(CIRCLE_CENTER):with_rotation(-90)
        end
    end
elseif SUMMON_CIRCLE_STACK then
    -- i was bored and this is pretty cool
    _circle = {}
    for _, v in pairs(circle) do
        table.insert(_circle, v)
    end
    if #_circle > 1 then
        table.sort(_circle, (function(a, b)
            return #a > #b
        end))
    end
    voffset = 0
    for _, v in ipairs(_circle) do
        circle_i = 0
        circle_c = #v
        voffset = voffset + 0.5
        if circle_c <= 1 then
            for _, i in ipairs(v) do
                retval[i] = ItemPos(CIRCLE_CENTER + Vector3(0, voffset, 0)):with_rotation(-90)
            end
        else
            for _, i in ipairs(v) do
                rot = (circle_i / circle_c) * 2 * math.pi
                retval[i] = ItemPos(CIRCLE_CENTER + Vector3(CIRCLE_RADIUS * math.cos(rot), voffset, CIRCLE_RADIUS * math.sin(rot))):with_rotation(-math.floor((circle_i / circle_c) * 360 + 180))
                circle_i = circle_i + 1
            end
        end
    end
else
    _circle = {}
    for _, v in pairs(circle) do
        table.insert(_circle, v)
    end
    if #_circle > 1 then
        table.sort(_circle, (function(a, b)
            return #a < #b
        end))
    end
    circle_i = 1
    for _, v in ipairs(_circle) do
        for _, i in ipairs(v) do
            rot = (circle_i / circle_c) * 2 * math.pi
            retval[i] = ItemPos(CIRCLE_CENTER + Vector3(CIRCLE_RADIUS * math.cos(rot), 0, CIRCLE_RADIUS * math.sin(rot))):with_rotation(-math.floor((circle_i / circle_c) * 360 + 180))
            circle_i = circle_i + 1
        end
    end
end

cupboard_sort(retval, cupboard_top, cupboard_top_c, CUPBOARD_TOP)
cupboard_sort(retval, cupboard_shelf_a, cupboard_shelf_a_c, CUPBOARD_SHELF_A)
cupboard_sort(retval, cupboard_shelf_b, cupboard_shelf_b_c, CUPBOARD_SHELF_B)
cupboard_sort(retval, cupboard_shelf_c, cupboard_shelf_c_c, CUPBOARD_SHELF_C)
cupboard_sort(retval, cupboard_shelf_d, cupboard_shelf_d_c, CUPBOARD_SHELF_D)

return retval