-- DO NOT EDIT THIS FILE DIRECTLY
-- CREATE A COPY TO EDIT, OTHERWISE YOUR CHANGES MAY BE LOST ON UPDATES

cruiser_top = false

function randomize(position)
    return randomize_scaled(position, 0.05)
end

function randomize_scaled(position, scale)
    position.x = position.x + (math.random() - 0.5) * scale
    position.z = position.z + (math.random() - 0.5) * scale
    return position
end

function below(position)
    return randomize(raycast(position))
end

function cupboard_or(cupboard_pos, fallback_pos)
    if unlockables[UNLOCKABLE_CUPBOARD] then
        return ItemPos(randomize_scaled(raycast(cupboard_pos, TRANSFORM_CUPBOARD), 0.02)):with_parent(PARENT_CUPBOARD)
    elseif fallback_pos == nil then
        return nil
    else
        return randomize_scaled(raycast(fallback_pos), 0.02)
    end
end

function cupboard_or_rot(cupboard_pos, fallback_pos, fallback_rot)
    if unlockables[UNLOCKABLE_CUPBOARD] then
        return ItemPos(randomize_scaled(raycast(cupboard_pos, TRANSFORM_CUPBOARD), 0.02)):with_parent(PARENT_CUPBOARD)
    else
        return ItemPos(randomize_scaled(raycast(fallback_pos), 0.02)):with_rotation(fallback_rot)
    end
end

function first_x_on_cruiser(item, x, cruiser_pos, cruiser_top_pos, cruiser_rot, fallback_pos)
    if unlockables[UNLOCKABLE_CRUISER] and item.index - 1 < x and item.index < item.count then
        return ItemPos((function()
            if cruiser_top then
                return cruiser_top_pos
            else
                return cruiser_pos
            end
        end)()):with_parent(PARENT_CRUISER):with_rotation(cruiser_rot)
    else
        return fallback_pos
    end
end

retval = {}

-- Y
CUPBOARD_ABOVE = 3.2;
CUPBOARD_TOP = 2.4;
CUPBOARD_MIDDLE_1 = 2;
CUPBOARD_MIDDLE_2 = 1.5;
CUPBOARD_BOTTOM = 0.5;

-- Y
CRUISER_ABOVE = 2.4;
CRUISER_TOP = 1.17;
CRUISER_MIDDLE = 0.4;
CRUISER_BOTTOM = -0.12;
CRUISER_FLOOR = -0.5;

-- X
CRUISER_LEFT = -1.14
CRUISER_RIGHT = 1.14

-- Z
CRUISER_FRONT = 0.35

-- TODO: POSITION_TRASH = ItemPos(nil)

max_large = 1
max_small = 1
if moon.id == 3 then
    for i, v in pairs(items) do
        if not (v.name == "ClipboardManual" or v.name == "StickyNoteItem" or v.name == "ZeddogPlushie" or v.name == "KnifeItem" or v.name == "ShotgunItem") then
            -- skip these items, they are not included later
            if v.large then
                max_large = math.max(v.value, max_large)
            else
                max_small = math.max(v.value, max_small)
            end
        end
    end
end

shotguns_on_cruiser = 0
for i, v in pairs(items) do
    if v.name == "ClipboardManual" or v.name == "StickyNoteItem" then
        -- skip these items

    elseif v.name == "ZeddogPlushie" then
        if v.index == 1 then
            retval[i] = ItemPos(Vector3(-0.9, -0.75, 0.35)):with_relative(RELATIVE_TERMINAL)
        else
            retval[i] = below(Vector3(9, 1.21, -5.55)) -- TODO: POSITION put on terminal so its a lil terminal buddy
        end
    elseif v.name == "KnifeItem" then
        retval[i] = first_x_on_cruiser(v, 1, Vector3(CRUISER_RIGHT, CRUISER_TOP, -2.4), Vector3(-1.3, CRUISER_ABOVE, -3.7), -90, cupboard_or_rot(Vector3(-1.9, 0.6, CUPBOARD_MIDDLE_2), Vector3(-2.5, 3, -6.65), -90))
    elseif v.name == "ShotgunItem" then
        if v.type == "ShotgunItem" then
            if v.arg == 2 and shotguns_on_cruiser < 2 then
                shotguns_on_cruiser = shotguns_on_cruiser + 1
                retval[i] = ItemPos((function()
                    if cruiser_top then
                        return nil
                    else
                        return Vector3(CRUISER_RIGHT + 0.04, CRUISER_TOP, -1.2)
                    end
                end)()):with_parent(PARENT_CRUISER)
            else
                retval[i] = raycast(Vector3(8.9 - (0.15 * v.arg), 2, -5.5))
            end
        else
            retval[i] = raycast(Vector3(9.05, 2, -5.5))
        end


    elseif moon.id == 3 and v.scrap then
        -- Company Building, put scrap near the desk
        if v.large then
            retval[i] = Vector3(-28, -2.9, -26 + (v.value - max_large) * 0.1)
        else
            retval[i] = Vector3(-28, -2.9, -22 - (v.value - max_small) * 0.1)
        end



        -- TODO: POSITION cruiser_top_pos
    elseif v.name == "LungApparatus" then
        retval[i] = below(Vector3(-6.8, 4.4, -6.65))
    elseif v.name == "KiwiBabyItem" then
        retval[i] = below(Vector3(4.85, 2, -4))
    elseif v.name == "RedLocustHive" then
        retval[i] = below(Vector3(-6.8, 4.4, -5.65))
    elseif v.name == "SoccerBall" then
        retval[i] = below(Vector3(-6.8, 4.4, -7.75))
    elseif v.name == "WhoopieCushion" then
        retval[i] = below(Vector3(9, 2, -8.25))

    elseif v.name == "WalkieTalkie" then
        retval[i] = cupboard_or(Vector3(-1.4, 0.6, CUPBOARD_TOP), Vector3(-3.7, 3, -6.6))
    elseif v.name == "BBFlashlight" then
        retval[i] = cupboard_or(Vector3(-1.3, 0.2, CUPBOARD_MIDDLE_1), Vector3(-4.1, 3, -6.6))
    elseif v.name == "ShovelItem" then
        retval[i] = first_x_on_cruiser(v, 4, Vector3(CRUISER_RIGHT, CRUISER_MIDDLE, -2), Vector3(-1.3, CRUISER_ABOVE, -3.7), -90, cupboard_or_rot(Vector3(-1.5, 0.3, CUPBOARD_MIDDLE_2), Vector3(-4.5, 3, -6.8), -90))
    elseif v.name == "LockPickerItem" then
        retval[i] = cupboard_or_rot(Vector3(-2, 0.5, CUPBOARD_TOP), Vector3(-1.8, 3, -6.8), 90)
    elseif v.name == "FlashlightItem" then
        retval[i] = cupboard_or(Vector3(-1.3, 0.65, CUPBOARD_MIDDLE_1), Vector3(-4.1, 3, -7.2))
    elseif v.name == "StunGrenade" then
        retval[i] = cupboard_or_rot(Vector3(-1.2, 0.5, CUPBOARD_MIDDLE_1), Vector3(-3.7, 3, -7.35), -90)
    elseif v.name == "Boombox" then
        retval[i] = cupboard_or(Vector3(-0.3, 0.5, CUPBOARD_ABOVE), Vector3(-1.1, 3, -6.8))
    elseif v.name == "TZPChemical" then
        retval[i] = cupboard_or_rot(Vector3(-0.55, 0.2, CUPBOARD_MIDDLE_1), Vector3(-3.3, 3, -6.525), -90)
    elseif v.name == "PatcherGunItem" then
        retval[i] = cupboard_or_rot(Vector3(-1.1, 0.6, CUPBOARD_TOP), Vector3(-4.9, 3, -6.5), -90)
    elseif v.name == "JetpackItem" then
        retval[i] = cupboard_or(Vector3(-0.3, 0.2, CUPBOARD_BOTTOM), Vector3(-5.8, 3, -6.8))
    elseif v.name == "SprayPaintItem" then
        retval[i] = cupboard_or_rot(Vector3(-1.7, 0.5, CUPBOARD_MIDDLE_1), Vector3(-3.3, 3, -7.3), -90)
    elseif v.name == "WeedKillerItem" then
        retval[i] = first_x_on_cruiser(v, math.huge, Vector3(CRUISER_RIGHT, CRUISER_MIDDLE, -0.77), Vector3(-0.9, CRUISER_ABOVE, -3.7), -90, cupboard_or_rot(Vector3(-2.05, 0.5, CUPBOARD_MIDDLE_1), Vector3(-2.5, 3, -7.3), -90))
    elseif v.name == "BeltBagItem" then
        if v.type == "BeltBagItem" and v.arg > 0 then
            retval[i] = cupboard_or(Vector3(-0.35, 0.5, CUPBOARD_TOP), Vector3(-5, 3, -7.85))
        else
            retval[i] = cupboard_or(Vector3(-0.35, 0.5, CUPBOARD_TOP), Vector3(-5, 3, -7.1))
        end
    elseif v.name == "Key" then
        retval[i] = first_x_on_cruiser(v, 4, Vector3(CRUISER_LEFT, CRUISER_MIDDLE, -0.7), Vector3(-0.9, CRUISER_ABOVE, -3.3), -90, cupboard_or(Vector3(-0.3, 0.6, CUPBOARD_MIDDLE_2), Vector3(8.6, 2, -6.6)))
    elseif v.name == "ShotgunShell" then
        retval[i] = first_x_on_cruiser(v, 2, Vector3(CRUISER_LEFT, CRUISER_TOP, -0.7), Vector3(-0.9, CRUISER_ABOVE, -3.7), -90, cupboard_or(Vector3(-0.3, 0.6, CUPBOARD_MIDDLE_1), Vector3(8.75, 2, -6.05)))

    elseif v.name == "RadarBoosterDevice" then
        retval[i] = first_x_on_cruiser(v, 1, Vector3(0, CRUISER_BOTTOM, CRUISER_FRONT), Vector3(-1.3, CRUISER_ABOVE, -3.7), 0, cupboard_or(Vector3(-2, 0.6, 0.5), nil)) -- TODO: POSITION proper fallback position


    elseif not v.scrap then
        -- Tool item
        retval[i] = cupboard_or(Vector3(-2, 0.6, 0.5), nil)
    elseif v.large then
        -- Two hand item
        retval[i] = below(Vector3(-4.5, 3, -5.25))
    else
        -- One hand item
        retval[i] = below(Vector3(-2.25, 3, -5.25))
    end
end

return retval